apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceId
          datasourceUid: tempo
  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: traceId=\"([a-z0-9_]+)\"
          name: TraceID
          url: $${__value__.raw}
  - name: Tempo
    type: tempo
    url: http://tempo:3200