server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_set_header x-request-id $http_x_request_id;
        proxy_connect_timeout 2s;
        proxy_read_timeout 5s;
    }
}
