apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
  namespace: week3
  labels:
    app: crashloop
    lesson: failure
spec:
  restartPolicy: Always
  containers:
    - name: crash
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
        - echo "intentional crash for W3D5"; sleep 2; exit 1
