apiVersion: v1
kind: Pod
metadata:
  name: bad-image-pod
  namespace: week3
  labels:
    app: bad-image
    lesson: failure
spec:
  containers:
    - name: nginx
      image: nginx:not-a-real-tag
      ports:
        - name: http
          containerPort: 80
