apiVersion: v1
kind: Service
metadata:
  name: runtime-api
  namespace: week4
  labels:
    app: runtime-api
spec:
  type: ClusterIP
  selector:
    app: runtime-api
  ports:
    - name: http
      port: 80
      targetPort: http

