server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location /identity/ {
    proxy_pass http://identity-api:3000/;
  }

  location /payment/ {
    proxy_pass http://payment-api:3000/;
  }
}
